### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by remotevase** [PocketEssential/UltraFaction#2]
Just wanted to help you by making an updated todo list! Feel free to check off the boxes when completed!
- [x] MassiveEconomy Support 
- [x] EconomyPlus Support (IDK if u want this or not, feel free to edit it out)
- [ ] Add MySQL or SQL support
- [ ] Is Player In Faction? Public Function [here](https://github.com/PocketEssential/UltraFaction/blob/14b351cd4ea96eb2d08a65c9ffe5840cf6dd3bc8/src/PocketEssential/UltraFaction/UltraFaction.php#L106)
- [ ] UltraFaction Help list
- [ ] Other Events in Commands File (IDK what u mean, so [here](https://github.com/PocketEssential/UltraFaction/blob/f71d853e06f99ddaf73ad575881a661217a35714/src/PocketEssential/UltraFaction/commands/Commands.php#L72) is link to it)
- [ ] Add "**_Is Player In Faction? Public Function [here](https://github.com/PocketEssential/UltraFaction/blob/14b351cd4ea96eb2d08a65c9ffe5840cf6dd3bc8/src/PocketEssential/UltraFaction/UltraFaction.php#L106)_**" to the Commands File (Line 96)
- [ ] /f war command
- [ ] /f map command
- [ ] /f ally command
- [ ] /f unally command
- [ ] /f claim command
- [ ] /f invite command
- [ ] /f kick command
- [x] Approve Pull Request #1 so that the grammar is fixed
- [ ]  Add sqlite or lite support
- [ ] /f deny command
- [ ] /f delete command
- [x] Add ascii to all files.
- [ ] Add the following variables:
                         {ultrafaction_name} Get's replaced with the player faction name
                         {ultrafaction_level} Get's replaced with the faction level
- [ ] Convince PureChat and PurePerms to add support for this plugin
### Add the most common languages (listed below)
- [x] English
- [x] French
- [ ] Mandarin
- [x] Spanish
- [ ] Hindu
- [ ] Arabic
- [x] Portuguese
- [ ] Bengali
- [ ] Russian
- [ ] Japanese
- [ ] Punjabi

**Comment by remotevase** [comment]
Also, my personal opinion is that instead of having PocketEssential ascii, you should use this instead:
```
 _    _ _ _             ______         _   _                 
| |  | | | |           |  ____|       | | (_)                
| |  | | | |_ _ __ __ _| |__ __ _  ___| |_ _  ___  _ __  ___ 
| |  | | | __| '__/ _` |  __/ _` |/ __| __| |/ _ \| '_ \/ __|
| |__| | | |_| | | (_| | | | (_| | (__| |_| | (_) | | | \__ \
 \____/|_|\__|_|  \__,_|_|  \__,_|\___|\__|_|\___/|_| |_|___/
```

**Comment by remotevase** [comment]
I am going to add another pull request that adds ascii + a message to each file

**Comment by xZeroMCPE** [comment]
Ah, thanks alot.

**Comment by ghost** [comment]
Is Economy things needed?

**Comment by xZeroMCPE** [comment]
nope

**Comment by remotevase** [comment]
Added the languages

**Comment by xZeroMCPE** [comment]
Added economy support such as:
- EconomyAPI
- MassiveEconomy

**Comment by PrimusLV** [comment]
You can handle languages way more easier with [Localizer](https://github.com/Chris-Prime/Localizer)
Nice job 👍

**Comment by PrimusLV** [comment]
> Other Events in Commands File (IDK what u mean, so here is link to it)

Trigger [events](https://github.com/Chris-Prime/FactionsPE/tree/reborn/src/factions/event/faction)?

**Comment by xZeroMCPE** [comment]
Yeah, maybe. Might have to rewrite the data providers / some part of it.

**Comment by SinlesFlyer376** [comment]
Is it possible to set up the faction in the format of the rank? So other people know what faction you are in?

**Comment by xZeroMCPE** [comment]
Yes, I'm planing on adding those varibles.

{ultrafaction_name} - Get's replaced with the player faction name
{ultrafaction_level} - Get's replaced with the faction level

etc

**Comment by SinlesFlyer376** [comment]
Why won't ultrafaction work on my server? Dm me on twitter @Sinles_Flyer376 for questions of mine

**Comment by remotevase** [comment]
@xZeroMCPE that should work, then

**Comment by xZeroMCPE** [comment]
@remotevase Yeah, and + plugin is not finished and PurePerms / PureChat will need to add support for it.

**Comment by remotevase** [comment]
Okay, I'll add to the list on top

**Comment by xZeroMCPE** [comment]
Okay

**Comment by SinlesFlyer376** [comment]
ZeroMC can you DM me on twitter @Sinles_Flyer376

**Comment by xZeroMCPE** [comment]
Your dm's are closed . Here's my username (@xZeroMCPE)

**Comment by SinlesFlyer376** [comment]
OK they are open now :) DM me when you have finished the pureperms and Purechat

**Comment by SinlesFlyer376** [comment]
y can't you rewrite purechat and pureperms and then call it something else but have a different Code sorta and contributes can help with it

**Comment by xZeroMCPE** [comment]
Well, We're planning on making a group manager plugin + chat etc.

**Comment by ghost** [comment]
Sounds Awesome! 😄

**Comment by xZeroMCPE** [comment]
https://github.com/PocketEssential/PocketPerms

**Comment by ghost** [comment]
saw it already

**Comment by GoldCodes** [comment]
Added Spanish!

**Comment by remotevase** [comment]
Great!

**Comment by EndreEndi** [comment]
PLEASE ADD PURECHAT. SUPPORT

**Comment by xZeroMCPE** [comment]
PureChat has to add our upport

**Comment by remotevase** [comment]
We  can make a modified PureChat version but that requires actual effort

**Comment by xZeroMCPE** [comment]
@remotevase Well, it's pretty easy / simple!

**Comment by remotevase** [comment]
yes it is easy and simple but it requires effort no matter what

**Comment by xZeroMCPE** [comment]
lol

**Comment by PrimusLV** [comment]
https://github.com/PurePlugins/PureChat/pull/55 That's how I added support for my plugin

**Comment by xZeroMCPE** [comment]
Yeah, hate the fact it didn't get merged :/ 

can't wait to finish

PocketPerm!

**Comment by remotevase** [comment]
:P

**Comment by ghost** [comment]
@xZeroMCPE I added isPlayerInFaction. Can you check that?

**Comment by xZeroMCPE** [comment]
@ankitmaharjan252 Okay, will do.

**Comment by ghost** [comment]
Okay sure

**Comment by xZeroMCPE** [comment]
@ankitmaharjan252 Maybe we can change how faction things are stored, like maybe sq lite as default, instead of yml... It's more faster...

**Comment by ghost** [comment]
Yea i was thinking that too!

**Comment by xZeroMCPE** [comment]
@ankitmaharjan252 Yeah, Lets to that..... And i think you should test things, and not depend on other(s) to test for you..

**Comment by ghost** [comment]
I can't cause ..... You know it

**Comment by xZeroMCPE** [comment]
@ankitmaharjan252 Okay, Well its fine. 👍

**Comment by inxomnyaa** [comment]
suggestion: change 'Resources' to 'resources'. pmmp might not detect the resources in some cases. (same for any uppercase folder.. Languages etc)

**Comment by xZeroMCPE** [comment]
Yeah, I thought about that. Gonna do it soon.

**Comment by legoboy0215** [comment]
And, you are reading from the json files on the fly? You should cache those.

**Comment by xZeroMCPE** [comment]
@legoboy0215 Yeah, I have plans of doing. Just busy as of now to continue UltraFaction.

**Comment by Wolfkid200444** [comment]
@xZeroMCPE Does Ultra factions suport pureperms and purechat?

**Comment by xZeroMCPE** [comment]
@Wolfkid200444 Yeah

**Comment by Wolfkid200444** [comment]
Does UltraFactions Support 3.1.3? @xZeroMCPE

**Comment by xZeroMCPE** [comment]
@Wolfkid200444 No

**Comment by Wolfkid200444** [comment]
@xZeroMCPE Will the plugin be Updated?

**Comment by xZeroMCPE** [comment]
@Wolfkid200444 Uhm, don't know.

**Comment by xZeroMCPE** [comment]
@Wolfkid200444 I'll work and get this bad boy finished!

**Comment by Wolfkid200444** [comment]
Thanks Man!!
